// [Not yet quite] automatically generated by pepper-fuzzer 0.1
// zulla@zulla.org


// PepperPDF

try {
  pepper_pdf.accessibility('-0.00001'); 
  pepper_pdf.accessibility(-0.00001) 
  pepper_pdf.documentLoadComplete('-0.00001'); 
  pepper_pdf.documentLoadComplete(-0.00001) 
  pepper_pdf.getHeight('-0.00001'); 
  pepper_pdf.getHeight(-0.00001) 
  pepper_pdf.getHorizontalScrollbarThickness('-0.00001'); 
  pepper_pdf.getHorizontalScrollbarThickness(-0.00001) 
  pepper_pdf.getPageLocationNormalized('-0.00001'); 
  pepper_pdf.getPageLocationNormalized(-0.00001) 
  pepper_pdf.getVerticalScrollbarThickness('-0.00001'); 
  pepper_pdf.getVerticalScrollbarThickness(-0.00001) 
  pepper_pdf.getWidth('-0.00001'); 
  pepper_pdf.getWidth(-0.00001) 
  pepper_pdf.getZoomLevel('-0.00001'); 
  pepper_pdf.getZoomLevel(-0.00001) 
  pepper_pdf.goToPage('-0.00001'); 
  pepper_pdf.goToPage(-0.00001) 
  pepper_pdf.grayscale('-0.00001'); 
  pepper_pdf.grayscale(-0.00001) 
  pepper_pdf.loadPreviewPage('-0.00001'); 
  pepper_pdf.loadPreviewPage(-0.00001) 
  pepper_pdf.onload('-0.00001'); 
  pepper_pdf.onload(-0.00001) 
  pepper_pdf.onPluginSizeChanged('-0.00001'); 
  pepper_pdf.onPluginSizeChanged(-0.00001) 
  pepper_pdf.onScroll('-0.00001'); 
  pepper_pdf.onScroll(-0.00001) 
  pepper_pdf.pageXOffset('-0.00001'); 
  pepper_pdf.pageXOffset(-0.00001) 
  pepper_pdf.pageYOffset('-0.00001'); 
  pepper_pdf.pageYOffset(-0.00001) 
  pepper_pdf.printPreviewPageCount('-0.00001'); 
  pepper_pdf.printPreviewPageCount(-0.00001) 
  pepper_pdf.reload('-0.00001'); 
  pepper_pdf.reload(-0.00001) 
  pepper_pdf.removePrintButton('-0.00001'); 
  pepper_pdf.removePrintButton(-0.00001) 
  pepper_pdf.resetPrintPreviewUrl('-0.00001'); 
  pepper_pdf.resetPrintPreviewUrl(-0.00001) 
  pepper_pdf.sendKeyEvent('-0.00001'); 
  pepper_pdf.sendKeyEvent(-0.00001) 
  pepper_pdf.setPageNumbers('-0.00001'); 
  pepper_pdf.setPageNumbers(-0.00001) 
  pepper_pdf.setPageXOffset('-0.00001'); 
  pepper_pdf.setPageXOffset(-0.00001) 
  pepper_pdf.setPageYOffset('-0.00001'); 
  pepper_pdf.setPageYOffset(-0.00001) 
  pepper_pdf.setZoomLevel('-0.00001'); 
  pepper_pdf.setZoomLevel(-0.00001) 
  pepper_pdf.fitToHeight('-0.00001'); 
  pepper_pdf.fitToHeight(-0.00001) 
  pepper_pdf.fitToWidth('-0.00001'); 
  pepper_pdf.fitToWidth(-0.00001) 
  pepper_pdf.zoomIn('-0.00001'); 
  pepper_pdf.zoomIn(-0.00001) 
  pepper_pdf.zoomOut('-0.00001'); 
  pepper_pdf.zoomOut(-0.00001) 
  pepper_pdf.('-0.00001'); 
  pepper_pdf.(-0.00001)"
} catch (e) {
  alert(e);
}

// PepperFlash

try {
  pepper_swf.__flash__request('-0.00001'); 
  pepper_swf.__flash__request(-0.00001) 
  pepper_swf.CallFunction('-0.00001'); 
  pepper_swf.CallFunction(-0.00001) 
  pepper_swf.CurrentFrame('-0.00001'); 
  pepper_swf.CurrentFrame(-0.00001) 
  pepper_pdf.FlashVersion('-0.00001'); 
  pepper_swf.FlashVersion(-0.00001) 
  pepper_swf.FrameLoaded('-0.00001'); 
  pepper_swf.FrameLoaded(-0.00001) 
  pepper_swf.GetVariable('-0.00001'); 
  pepper_swf.GetVariable(-0.00001) 
  pepper_swf.GotoFrame('-0.00001'); 
  pepper_swf.GotoFrame(-0.00001) 
  pepper_swf.IsPlaying('-0.00001'); 
  pepper_swf.IsPlaying(-0.00001) 
  pepper_swf.LoadMovie('-0.00001'); 
  pepper_swf.LoadMovie(-0.00001) 
  pepper_swf.Pan('-0.00001'); 
  pepper_swf.Pan(-0.00001) 
  pepper_swf.PercentLoaded('-0.00001'); 
  pepper_swf.PercentLoaded(-0.00001) 
  pepper_swf.Play('-0.00001'); 
  pepper_swf.Play(-0.00001) 
  pepper_swf.SetReturnValue('-0.00001'); 
  pepper_swf.SetReturnValue(-0.00001) 
  pepper_swf.SetVariable('-0.00001'); 
  pepper_swf.SetVariable(-0.00001) 
  pepper_swf.SetZoomRect('-0.00001'); 
  pepper_swf.SetZoomRect(-0.00001) 
  pepper_swf.StopPlay('-0.00001'); 
  pepper_swf.StopPlay(-0.00001) 
  pepper_swf.TCallFrame('-0.00001'); 
  pepper_swf.TCallFrame(-0.00001) 
  pepper_swf.TCallLabel('-0.00001'); 
  pepper_swf.TCallLabel(-0.00001) 
  pepper_swf.TCurrentFrame('-0.00001'); 
  pepper_swf.TCurrentFrame(-0.00001) 
  pepper_swf.TCurrentLabel('-0.00001'); 
  pepper_swf.TCurrentLabel(-0.00001) 
  pepper_swf.TGetProperty('-0.00001'); 
  pepper_swf.TGetProperty(-0.00001) 
  pepper_swf.TGetPropertyAsNumber('-0.00001'); 
  pepper_swf.TGetPropertyAsNumber(-0.00001) 
  pepper_swf.TGetPropertyNum('-0.00001'); 
  pepper_swf.TGetPropertyNum(-0.00001) 
  pepper_swf.TGotoFrame('-0.00001'); 
  pepper_swf.TGotoFrame(-0.00001) 
  pepper_swf.TGotoLabel('-0.00001'); 
  pepper_swf.TGotoLabel(-0.00001) 
  pepper_swf.TPlay('-0.00001'); 
  pepper_swf.TPlay(-0.00001) 
  pepper_swf.TSetProperty('-0.00001'); 
  pepper_swf.TSetProperty(-0.00001) 
  pepper_swf.TStopPlay('-0.00001'); 
  pepper_swf.TStopPlay(-0.00001) 
  pepper_swf.TotalFrames('-0.00001'); 
  pepper_swf.TotalFrames(-0.00001) 
  pepper_swf.Zoom('-0.00001'); 
  pepper_swf.Zoom(-0.00001) 
} catch (e) {
  alert(e);
}
